[workspace]
members = [
    "crates/*",
]

[workspace.dependencies]
axum = "0.6.18"
eyre = "0.6.8"
reqwest = { version = "0.11.12", default-features = false, features = ["json", "gzip", "rustls-tls"] }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.97"
thiserror = "1.0.37"
tokio = { version = "1.28.2", features = ["full"]}
tower = "0.4.13"
tracing = "0.1.36"
url = "2.3.1"
