---
apiVersion: v1
kind: Namespace
metadata:
  name: saasaparilla-notification
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver
  namespace: saasaparilla-notification
  labels:
    app.kubernetes.io/component: receiver
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: receiver
  template:
    metadata:
      labels:
        app.kubernetes.io/component: receiver
    spec:
      containers:
        - name: receiver
          image: localhost:5000/saasaparilla/notification/receiver:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: director
  namespace: saasaparilla-notification
  labels:
    app.kubernetes.io/component: director
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: director
  template:
    metadata:
      labels:
        app.kubernetes.io/component: director
    spec:
      containers:
        - name: director
          image: localhost:5000/saasaparilla/notification/director:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributor
  namespace: saasaparilla-notification
  labels:
    app.kubernetes.io/component: distributor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: distributor
  template:
    metadata:
      labels:
        app.kubernetes.io/component: distributor
    spec:
      containers:
        - name: distributor
          image: localhost:5000/saasaparilla/notification/distributor:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: receiver
  namespace: saasaparilla-notification
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: receiver
  sessionAffinity: ClientIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: director
  namespace: saasaparilla-notification
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: director
  sessionAffinity: ClientIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: distributor
  namespace: saasaparilla-notification
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: distributor
  sessionAffinity: ClientIP
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: saasaparilla-notification
spec:
  type: ExternalName
  externalName: kafka.kafka.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: saasaparilla-notification
spec:
  type: ExternalName
  externalName: redis.redis.svc.cluster.local
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: saasaparilla-notification
spec:
  type: ExternalName
  externalName: postgres.postgres.svc.cluster.local
