---
apiVersion: v1
kind: Namespace
metadata:
  name: saasaparilla-notification
---
apiVersion: v1
kind: Pod
metadata:
  name: saasaparilla-notification
  namespace: saasaparilla-notification
  labels:
    app: saasaparilla-notification
spec:
  containers:
    - name: receiver
      image: localhost:5000/saasaparilla/notification/receiver:latest
      ports:
        - containerPort: 8080
    - name: director
      image: localhost:5000/saasaparilla/notification/director:latest
      ports:
        - containerPort: 8080
    - name: distributor
      image: localhost:5000/saasaparilla/notification/distributor:latest
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: saasaparilla-notification
spec:
  type: ExternalName
  externalName: kafka.kafka.svc.cluster.local
