---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 1h #minimize impact on GitHub's servers - users can `flux reconcile` if they manually screw with something
  url: https://kubernetes-sigs.github.io/metrics-server
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: flux-system
spec:
  interval: 10m #this only hits the locally cached chart registry
  timeout: 1m
  chart:
    spec:
      chart: metrics-server
      version: 3.12.2
      sourceRef:
        kind: HelmRepository
        name: metrics-server
  releaseName: metrics-server
  targetNamespace: kube-system
  storageNamespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: enabled
  values:
    args:
      # E0606 17:23:09.841625 1 [scraper.go:149]
      # "Failed to scrape node"
      #   err="Get \"https://172.18.0.5:10250/metrics/resource\":
      #     tls: failed to verify certificate:
      #     x509: cannot validate certificate for 172.18.0.5 because it doesn't contain any IP SANs"
      #   node="saasaparilla-notification-control-plane"
      - "--kubelet-insecure-tls"
---
