---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 1h #minimize impact on nginx's servers - users can `flux reconcile` if they manually screw with something
  url: https://kubernetes.github.io/ingress-nginx
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  interval: 10m #this only hits the locally cached chart registry
  timeout: 1m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.12.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx
  releaseName: ingress-nginx
  targetNamespace: ingress-nginx
  storageNamespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: enabled
  values:
    controller.nodeSelector: 'node-role.kubernetes.io/control-plane: ""'
    controller.tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: Exists
    controller.admissionWebhooks.patch.nodeSelector: 'node-role.kubernetes.io/control-plane: ""'
    controller.admissionWebhooks.patch.tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: Exists
    defaultBackend.nodeSelector: 'node-role.kubernetes.io/control-plane: ""'
    defaultBackend.tolerations:
      - key: "node-role.kubernetes.io/control-plane"
        operator: Exists
    namespaceOverride: "ingress-nginx"
---
