apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: bitnami-postgresql
  namespace: flux-system
spec:
  interval: 1h #minimize impact on dockerhub's servers - users can `flux reconcile` if they manually screw with something
  url: oci://registry-1.docker.io/saasaparillacharts/postgresql
  ref:
    tag: "16.7.10"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: flux-system
spec:
  interval: 10m #this only hits the locally cached chart registry
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: bitnami-postgresql
  releaseName: postgresql
  targetNamespace: infra
  storageNamespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: enabled
  postRenderers:
    - kustomize:
        images:
          - name: bitnami/postgresql
            newName: saasaparilla/postgresql
          - name: bitnami/postgres-exporter
            newName: saasaparilla/postgres-exporter
          - name: bitnami/os-shell
            newName: saasaparilla/os-shell
  values:
    auth:
      postgresPassword: "admin_password"
      username: "saasaparilla_notification_service_account"
      password: "saasaparilla_notification_password"
      database: "saasaparilla_notification"
    primary:
      resourcesPreset: "micro"
    readReplicas:
      resourcesPreset: "micro"
    namespaceOverride: "infra"
---
