apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: bitnami-valkey
  namespace: flux-system
spec:
  interval: 1h #minimize impact on dockerhub's servers - users can `flux reconcile` if they manually screw with something
  url: oci://registry-1.docker.io/saasaparillacharts/valkey
  ref:
    tag: "3.0.9"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: valkey
  namespace: flux-system
spec:
  interval: 10m #this only hits the locally cached chart registry
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: bitnami-valkey
  releaseName: valkey
  targetNamespace: infra
  storageNamespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: false
  driftDetection:
    mode: enabled
  postRenderers:
    - kustomize:
        images:
          - name: bitnami/valkey
            newName: saasaparilla/valkey
          - name: bitnami/valkey-exporter
            newName: saasaparilla/valkey-exporter
          - name: bitnami/valkey-sentinel
            newName: saasaparilla/valkey-sentinel
          - name: bitnami/os-shell
            newName: saasaparilla/os-shell
          - name: bitnami/kubectl
            newName: saasaparilla/kubectl
  values:
    auth:
      enabled: false
    primary:
      resourcesPreset: "micro"
    replica:
      resourcesPreset: "micro"
    namespaceOverride: "infra"
---
